### ISSUE TITLE
Use new /sync API

### ISSUE THREAD

**Issue by tdfischer** [tdfischer/pto#4]
Split out from #1.

PTO currently uses the old fashioned initialSync API. oob.systems does not yet use this version of synapse so this can be delayed for a bit.

> It should probably be calling /sync rather than /initialSync and /events - /sync is much simpler (albeit slghtly less performant on synapse currently)

**Comment by ara4n** [comment]
@tdfischer: please yell if the `/sync` response sucks.  In general we've found it to be way easier to work with (by unifying `/initialSync` and `/events`, and adding support for stuff like `/filter`s).  Removing roomIDs from the response was actually my request to avoid redundant roomIDs appearing in both the key to the event and the event itself.  You also get a bunch of other nice stuff with `/sync`, like support for 'gappy syncs' (where you either get a full absolute sync or an incremental delta per room, depending on how much changed since you last synced.  whereas `/events` is always an incremental delta, which could be huuuge if you haven't run the client recently)
